### ISSUE TITLE
How to make it work with glue configuration

### ISSUE THREAD

**Issue by no-more** [rse/hapi-plugin-websocket#3]
Hello,

First of all, thanks a lot this plugins seems to do exactly what I want.

But currently I was not able to make it start with my glue configuration. When I add the plugin to my config file I have the following error on startup : 
```
/usr/src/app/node_modules/ws/lib/WebSocketServer.js:63
TypeError: missing or invalid options
     at new WebSocketServer (/usr/src/app/node_modules/ws/lib/WebSocketServer.js:63:13)
     at method (/usr/src/app/node_modules/hapi-plugin-websocket/hapi-plugin-websocket.js:141:15)
     at Items.serial (/usr/src/app/node_modules/hapi/lib/server.js:418:18)
     at iterate (/usr/src/app/node_modules/items/lib/index.js:36:13)
     at Object.exports.serial (/usr/src/app/node_modules/items/lib/index.js:39:9)
     at module.exports.internals.Server.internals.Server._invoke (/usr/src/app/node_modules/hapi/lib/server.js:415:11)
     at Object._events.emit [as callback] (/usr/src/app/node_modules/hapi/lib/server.js:335:18)
     at internals.itemCallback (/usr/src/app/node_modules/podium/lib/index.js:297:10)
     at _combinedTickCallback (internal/process/next_tick.js:135:11)
     at process._tickCallback (internal/process/next_tick.js:180:9)
     at Function.Module.runMain (module.js:686:11)
     at startup (bootstrap_node.js:187:16)
     at bootstrap_node.js:608:3
```
This error is triggered when no port is defined in the option
When I add options with port in my glue configuration it does not seems to change anything, my settings does not seems to be sent to the plugin.

How should I pass the configuration ?

Thanks.

**Comment by rse** [comment]
Sorry, you have to be more specific. Can you show me your particular source code (part) which does not work? Check the sample-server.js in the source tree for a working example, too.
